---
users_groups:
  - name: tomcat

  - name: admins
    sudo_options: ALL
    sudo_nopassword: false

users:
  - name: ansible
    password: "1234"
    groups: 
      - name: sudo
    create_home: true
    state: present
    shell: /bin/bash
    ssh_pub_key_location: /root/.ssh/id_ed25519.pub

  - name: ghost
    password: "!"
    create_home: true
    state: present
    shell: /bin/bash
    ssh_pub_key_location: /root/.ssh/id_ed25519.pub

  - name: tomcat
    password: "!"
    create_home: true
    home: /opt/tomcat
    state: present
    shell: /bin/bash
    ssh_pub_key_location: /root/.ssh/id_ed25519.pub

  - name: admin01
    password: "1234"
    groups: 
      - name: admins
    state: present 
    create_home: true
    shell: /bin/bash
    ssh_pub_key_location: /root/.ssh/id_ed25519.pub
