--- 
# include_vars - loaded at task execution time
- name: Load variables dynamically
  ansible.builtin.include_vars:
    file: vars/tomcat-11-0-18.yml

- name: Get directory name of tomcat
  ansible.builtin.set_fact:
    tomcat_dir: "{{ tomcat_link | regex_search('(.*\\/)([\\w\\W]*)(\\.tar\\.gz)', '\\2') | first }}"

- name: Get Name of tar file
  ansible.builtin.set_fact:
    tomcat_tar: "{{ tomcat_link | regex_search('(.*\\/)([\\w\\W]*\\.tar\\.gz)', '\\2') | first }}"

- name: Check if Tomcat Version {{ tomcat_version }} is already existing
  ansible.builtin.stat:
    path: "/opt/tomcat/{{ tomcat_dir }}"
  register: tomcat_dir

- name: If Tomcat Version already exists, end role
  ansible.builtin.meta: end_role
  when: 
    - tomcat_dir.stat.exists

- name: create tomcat directory
  ansible.builtin.file: 
    path: /opt/tomcat/
    state: directory
    mode: 0755
    owner: tomcat
    group: tomcat

- name: create /var/log/tomcat directory
  ansible.builtin.file: 
    path: /var/log/tomcat/
    state: directory
    mode: 0755
    owner: tomcat
    group: tomcat

# TODO: variable instead of hard coded url
- name: Download tomcat
  ansible.builtin.get_url: 
    url: "{{ tomcat_link }}"
    dest: /opt/tomcat/
    mode: 0755
    owner: tomcat
    group: tomcat

- name: "-------------- Show variables --------------------"
  ansible.builtin.debug:
    msg: "DIR: {{ tomcat_dir }} ----- TAR: /opt/tomcat/{{ tomcat_tar }} \\n {{ tomcat_version }}"

# TODO: variable instead of hard coded path
- name: Unpack tar.gz file
  ansible.builtin.unarchive:
    src: "/opt/tomcat/{{ tomcat_tar }}"
    remote_src: yes
    dest: /opt/tomcat/
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Create Symlink for Tomcat
  ansible.builtin.file:
    src: "/opt/tomcat/{{ tomcat_dir }}"
    dest: /opt/tomcat/recent
    owner: tomcat
    group: tomcat
    state: link

- name: Configure logging.properties file
  ansible.builtin.replace:
    path: /opt/tomcat/recent/conf/logging.properties
    regexp: '(^.*\.juli\.AsyncFileHandler\.directory\s*=\s*)\$\{catalina\.base\}\/logs'
    replace: '\1/var/log/tomcat'   
    backup: yes

- name: Configure catalina.out output path
  ansible.builtin.copy: 
    dest: /opt/tomcat/recent/bin/setenv.sh
    owner: tomcat
    group: tomcat
    mode: 0755
    content: |
      #!/bin/bash
      export CATALINA_OUT=/var/log/tomcat/catalina.out

- name: Ensure lxml is installed
  ansible.builtin.package:
    name: python3-lxml
    state: present

- name: Set AccessLogValve directory to /var/log/tomcat
  ansible.builtin.xml:
    path: "/opt/tomcat/recent/conf/server.xml"
    xpath: '//Valve[@className="org.apache.catalina.valves.AccessLogValve"]'
    attribute: directory
    value: /var/log/tomcat

- name: Set Context Path to /opt/App/webapps
  ansible.builtin.xml:
    path: "/opt/tomcat/recent/conf/server.xml"
    xpath: '//Host[@name="localhost"]'
    attribute: appBase
    value: /opt/App/webapps

- name: Configure Spring Boot profile 
  ansible.builtin.lineinfile:
    path: /opt/tomcat/recent/conf/catalina.properties
    line: "{{ item }}"
    state: present
  with_items: 
    - ' '
    - '# Add Spring Boot Profile: dev or prod'
    - 'Dspring.profiles.active=prod'
 
- name: Create systemd service file for Tomcat
  ansible.builtin.copy:
    dest: /etc/systemd/system/tomcat.service
    content: |
      [Unit]
      Description=Apache Tomcat
      After=network.target

      [Service]
      Type=forking
      User=tomcat
      Group=tomcat
      ExecStart=/opt/tomcat/recent/bin/startup.sh
      ExecStop=/opt/tomcat/recent/bin/shutdown.sh
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Configure log rotation for Tomcat
  ansible.builtin.copy:
    dest: /etc/logrotate.d/tomcat
    owner: root
    group: root
    mode: 0644
    content: |
      /var/log/tomcat/*.log {
          # rotate on a daily basis
          daily

          # delte files older than 30 days
          rotate 30

          # first copy file, then set size of original log file to 0. 
          # Necessary because tomcat shouldn't be stopped
          copytruncate

          # compress backup files
          compress

          # compression rate
          compressoptions -9

          # delay compression, so that yesterday is still readable
          delaycompress

          # add date to backup file
          dateext

          # don't throw error if log file isn't existing
          missingok

          # if files are missing, don't throw error
          notifempty

          # create file as user tomcat and group tomcat
          create 0640 tomcat tomcat
      }

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable Tomcat service
  ansible.builtin.systemd:
    name: tomcat.service
    state: restarted
    enabled: true
