---
- name: Download packages from URL
  hosts: all
  vars_files: 
    - vault.yml
  become: true

  tasks:
    - name: Install acl package
      ansible.builtin.package:
        name: acl
        state: present

    - name: Install Java 21 JDK
      ansible.builtin.apt:
        name: openjdk-21-jdk
        state: present

    - name: Create tomcat user
      ansible.builtin.user:
        name: tomcat
        shell: /bin/sh
        create_home: no
        state: present

    - name: Create tomcat group
      ansible.builtin.group: 
        name: tomcat
        state: present

    - name: create tomcat directory
      file: 
        path: /opt/tomcat/
        state: directory
        mode: 0755
        owner: tomcat
        group: tomcat

    - name: Download tomcat
      ansible.builtin.get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.18/bin/apache-tomcat-11.0.18.tar.gz 
        dest: /opt/tomcat/
        mode: 0755
        owner: tomcat
        group: tomcat

    - name: Unpack tar.gz file
      ansible.builtin.unarchive:
          src: /opt/tomcat/apache-tomcat-11.0.18.tar.gz
          remote_src: yes
          dest: /opt/tomcat/
          owner: tomcat
          group: tomcat
          mode: 0755

    - name: Create systemd service file for Tomcat
      ansible.builtin.copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          ExecStart=/opt/tomcat/apache-tomcat-11.0.18/bin/startup.sh
          ExecStop=/opt/tomcat/apache-tomcat-11.0.18/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes       # startet Tomcat auch nach einem Reboot automatisch
