---
- name: Create Users by roles
  hosts: presentation
  vars_files: 
    - vars/vault.yml
    - vars/users.yml
  become: true

  roles:
    - role: users

- name: Install Apps
  hosts: presentation
  vars_files: 
    - vars/vault.yml
  become: true

  roles:
    - role: apps

